### ISSUE TITLE
baltic_AC_forwardNN.py etc. refer to non-existent paths

### ISSUE THREAD

**Issue by sakvaka** [bcdev/baltic-scripts#3]
Commit 4a5daa7e1ffbed35e2bc8de8ca262f79d0ad9c99 , where old NN paths were removed, made `baltic_AC_forwardNN.py` and `baltic_AC_backwardNN.py`on `master` dysfunctional as they still reference the old paths.

**Comment by marpet** [comment]
Hello Sakari,

thanks for pointing this out.
The file run.py has been updated. With this the execution should be possible.
Now there is also a brief [readme](https://github.com/bcdev/baltic-scripts/blob/master/README.md)  which explains how to use it.
